// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKSKkWubHSb45EL-M9EpovyQMvjZPnP-4',
    appId: '1:1058557199980:web:e83896328aca0e93237a49',
    messagingSenderId: '1058557199980',
    projectId: 'nexpay-62e04',
    authDomain: 'nexpay-62e04.firebaseapp.com',
    storageBucket: 'nexpay-62e04.firebasestorage.app',
    measurementId: 'G-LGPXTV6ZET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAgIkfpXX4sh84SQwgdAdCNrY1OxIgv04',
    appId: '1:1058557199980:android:ae3e41676c68d284237a49',
    messagingSenderId: '1058557199980',
    projectId: 'nexpay-62e04',
    storageBucket: 'nexpay-62e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbNKvAF-S2IHVmfjvC2t90QTi6E4pby2k',
    appId: '1:1058557199980:ios:60b58755d91f4e12237a49',
    messagingSenderId: '1058557199980',
    projectId: 'nexpay-62e04',
    storageBucket: 'nexpay-62e04.firebasestorage.app',
    iosBundleId: 'com.example.nexPayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbNKvAF-S2IHVmfjvC2t90QTi6E4pby2k',
    appId: '1:1058557199980:ios:60b58755d91f4e12237a49',
    messagingSenderId: '1058557199980',
    projectId: 'nexpay-62e04',
    storageBucket: 'nexpay-62e04.firebasestorage.app',
    iosBundleId: 'com.example.nexPayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKSKkWubHSb45EL-M9EpovyQMvjZPnP-4',
    appId: '1:1058557199980:web:18839ac8ede88f54237a49',
    messagingSenderId: '1058557199980',
    projectId: 'nexpay-62e04',
    authDomain: 'nexpay-62e04.firebaseapp.com',
    storageBucket: 'nexpay-62e04.firebasestorage.app',
    measurementId: 'G-S764ZLGY8N',
  );
}
